// <auto-generated />
using CinemaRoulette.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaRoulette.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CinemaRoulette.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "США"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Швейцария"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Франция"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Польша"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Великобритания"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Швеция"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Индия"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Испания"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Германия"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Италия"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Гонконг"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Германия (ФРГ)"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Австралия"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Канада"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Мексика"
                        },
                        new
                        {
                            Id = 16,
                            Title = "Япония"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Дания"
                        },
                        new
                        {
                            Id = 18,
                            Title = "Чехия"
                        },
                        new
                        {
                            Id = 19,
                            Title = "Ирландия"
                        },
                        new
                        {
                            Id = 20,
                            Title = "Люксембург"
                        },
                        new
                        {
                            Id = 21,
                            Title = "Китай"
                        },
                        new
                        {
                            Id = 22,
                            Title = "Норвегия"
                        },
                        new
                        {
                            Id = 23,
                            Title = "Нидерланды"
                        },
                        new
                        {
                            Id = 24,
                            Title = "Аргентина"
                        },
                        new
                        {
                            Id = 25,
                            Title = "Финляндия"
                        },
                        new
                        {
                            Id = 26,
                            Title = "Босния и Герцеговина"
                        },
                        new
                        {
                            Id = 27,
                            Title = "Австрия"
                        },
                        new
                        {
                            Id = 28,
                            Title = "Тайвань"
                        },
                        new
                        {
                            Id = 29,
                            Title = "Новая Зеландия"
                        },
                        new
                        {
                            Id = 30,
                            Title = "Бразилия"
                        },
                        new
                        {
                            Id = 31,
                            Title = "Чехословакия"
                        },
                        new
                        {
                            Id = 32,
                            Title = "Мальта"
                        },
                        new
                        {
                            Id = 33,
                            Title = "СССР"
                        },
                        new
                        {
                            Id = 34,
                            Title = "Россия"
                        },
                        new
                        {
                            Id = 35,
                            Title = "Югославия"
                        },
                        new
                        {
                            Id = 36,
                            Title = "Португалия"
                        },
                        new
                        {
                            Id = 37,
                            Title = "Румыния"
                        },
                        new
                        {
                            Id = 38,
                            Title = "Хорватия"
                        },
                        new
                        {
                            Id = 39,
                            Title = "ЮАР"
                        },
                        new
                        {
                            Id = 40,
                            Title = "Куба"
                        },
                        new
                        {
                            Id = 41,
                            Title = "Колумбия"
                        },
                        new
                        {
                            Id = 42,
                            Title = "Израиль"
                        },
                        new
                        {
                            Id = 43,
                            Title = "Намибия"
                        },
                        new
                        {
                            Id = 44,
                            Title = "Турция"
                        },
                        new
                        {
                            Id = 45,
                            Title = "Бельгия"
                        },
                        new
                        {
                            Id = 46,
                            Title = "Сальвадор"
                        },
                        new
                        {
                            Id = 47,
                            Title = "Исландия"
                        },
                        new
                        {
                            Id = 48,
                            Title = "Венгрия"
                        },
                        new
                        {
                            Id = 49,
                            Title = "Корея Южная"
                        },
                        new
                        {
                            Id = 50,
                            Title = "Лихтенштейн"
                        },
                        new
                        {
                            Id = 51,
                            Title = "Болгария"
                        },
                        new
                        {
                            Id = 52,
                            Title = "Филиппины"
                        },
                        new
                        {
                            Id = 53,
                            Title = "Доминикана"
                        },
                        new
                        {
                            Id = 54,
                            Title = ""
                        },
                        new
                        {
                            Id = 55,
                            Title = "Марокко"
                        },
                        new
                        {
                            Id = 56,
                            Title = "Таиланд"
                        },
                        new
                        {
                            Id = 57,
                            Title = "Кения"
                        },
                        new
                        {
                            Id = 58,
                            Title = "Пакистан"
                        },
                        new
                        {
                            Id = 59,
                            Title = "Иран"
                        },
                        new
                        {
                            Id = 60,
                            Title = "Панама"
                        },
                        new
                        {
                            Id = 61,
                            Title = "Аруба"
                        },
                        new
                        {
                            Id = 62,
                            Title = "Ямайка"
                        },
                        new
                        {
                            Id = 63,
                            Title = "Греция"
                        },
                        new
                        {
                            Id = 64,
                            Title = "Тунис"
                        },
                        new
                        {
                            Id = 65,
                            Title = "Кыргызстан"
                        },
                        new
                        {
                            Id = 66,
                            Title = "Пуэрто Рико"
                        },
                        new
                        {
                            Id = 67,
                            Title = "Казахстан"
                        },
                        new
                        {
                            Id = 68,
                            Title = "Югославия (ФР)"
                        },
                        new
                        {
                            Id = 69,
                            Title = "Алжир"
                        },
                        new
                        {
                            Id = 70,
                            Title = "Германия (ГДР)"
                        },
                        new
                        {
                            Id = 71,
                            Title = "Сингапур"
                        },
                        new
                        {
                            Id = 72,
                            Title = "Словакия"
                        },
                        new
                        {
                            Id = 73,
                            Title = "Афганистан"
                        },
                        new
                        {
                            Id = 74,
                            Title = "Индонезия"
                        },
                        new
                        {
                            Id = 75,
                            Title = "Перу"
                        },
                        new
                        {
                            Id = 76,
                            Title = "Бермуды"
                        },
                        new
                        {
                            Id = 77,
                            Title = "Монако"
                        },
                        new
                        {
                            Id = 78,
                            Title = "Зимбабве"
                        },
                        new
                        {
                            Id = 79,
                            Title = "Вьетнам"
                        },
                        new
                        {
                            Id = 80,
                            Title = "Антильские Острова"
                        },
                        new
                        {
                            Id = 81,
                            Title = "Саудовская Аравия"
                        },
                        new
                        {
                            Id = 82,
                            Title = "Танзания"
                        },
                        new
                        {
                            Id = 83,
                            Title = "Ливия"
                        },
                        new
                        {
                            Id = 84,
                            Title = "Ливан"
                        },
                        new
                        {
                            Id = 85,
                            Title = "Кувейт"
                        },
                        new
                        {
                            Id = 86,
                            Title = "Египет"
                        },
                        new
                        {
                            Id = 87,
                            Title = "Литва"
                        },
                        new
                        {
                            Id = 88,
                            Title = "Венесуэла"
                        },
                        new
                        {
                            Id = 89,
                            Title = "Словения"
                        },
                        new
                        {
                            Id = 90,
                            Title = "Чили"
                        },
                        new
                        {
                            Id = 91,
                            Title = "Багамы"
                        },
                        new
                        {
                            Id = 92,
                            Title = "Эквадор"
                        },
                        new
                        {
                            Id = 93,
                            Title = "Коста-Рика"
                        },
                        new
                        {
                            Id = 94,
                            Title = "Кипр"
                        },
                        new
                        {
                            Id = 95,
                            Title = "Уругвай"
                        },
                        new
                        {
                            Id = 96,
                            Title = "Ирак"
                        },
                        new
                        {
                            Id = 97,
                            Title = "Мартиника"
                        },
                        new
                        {
                            Id = 98,
                            Title = "Эстония"
                        },
                        new
                        {
                            Id = 99,
                            Title = "ОАЭ"
                        },
                        new
                        {
                            Id = 100,
                            Title = "Бангладеш"
                        },
                        new
                        {
                            Id = 101,
                            Title = "Македония"
                        },
                        new
                        {
                            Id = 102,
                            Title = "Гвинея"
                        },
                        new
                        {
                            Id = 103,
                            Title = "Иордания"
                        },
                        new
                        {
                            Id = 104,
                            Title = "Латвия"
                        },
                        new
                        {
                            Id = 105,
                            Title = "Армения"
                        },
                        new
                        {
                            Id = 106,
                            Title = "Украина"
                        },
                        new
                        {
                            Id = 107,
                            Title = "Сирия"
                        },
                        new
                        {
                            Id = 108,
                            Title = "Шри-Ланка"
                        },
                        new
                        {
                            Id = 109,
                            Title = "Нигерия"
                        },
                        new
                        {
                            Id = 110,
                            Title = "Берег Слоновой кости"
                        },
                        new
                        {
                            Id = 111,
                            Title = "Грузия"
                        },
                        new
                        {
                            Id = 112,
                            Title = "Сенегал"
                        },
                        new
                        {
                            Id = 113,
                            Title = "Монголия"
                        },
                        new
                        {
                            Id = 114,
                            Title = "Габон"
                        },
                        new
                        {
                            Id = 115,
                            Title = "Замбия"
                        },
                        new
                        {
                            Id = 116,
                            Title = "Албания"
                        },
                        new
                        {
                            Id = 117,
                            Title = "Камерун"
                        },
                        new
                        {
                            Id = 118,
                            Title = "Буркина-Фасо"
                        },
                        new
                        {
                            Id = 119,
                            Title = "Узбекистан"
                        },
                        new
                        {
                            Id = 120,
                            Title = "Малайзия"
                        },
                        new
                        {
                            Id = 121,
                            Title = "Сербия"
                        },
                        new
                        {
                            Id = 122,
                            Title = "Гана"
                        },
                        new
                        {
                            Id = 123,
                            Title = "Таджикистан"
                        },
                        new
                        {
                            Id = 124,
                            Title = "Гаити"
                        },
                        new
                        {
                            Id = 125,
                            Title = "Конго (ДРК)"
                        },
                        new
                        {
                            Id = 126,
                            Title = "Гватемала"
                        },
                        new
                        {
                            Id = 127,
                            Title = "Российская империя"
                        },
                        new
                        {
                            Id = 128,
                            Title = "Беларусь"
                        },
                        new
                        {
                            Id = 129,
                            Title = "Молдова"
                        },
                        new
                        {
                            Id = 130,
                            Title = "Азербайджан"
                        },
                        new
                        {
                            Id = 131,
                            Title = "Палестина"
                        },
                        new
                        {
                            Id = 132,
                            Title = "Оккупированная Палестинская территория"
                        },
                        new
                        {
                            Id = 133,
                            Title = "Корея Северная"
                        },
                        new
                        {
                            Id = 134,
                            Title = "Никарагуа"
                        },
                        new
                        {
                            Id = 135,
                            Title = "Камбоджа"
                        },
                        new
                        {
                            Id = 136,
                            Title = "Ангола"
                        },
                        new
                        {
                            Id = 137,
                            Title = "Сербия и Черногория"
                        },
                        new
                        {
                            Id = 138,
                            Title = "Непал"
                        },
                        new
                        {
                            Id = 139,
                            Title = "Бенин"
                        },
                        new
                        {
                            Id = 140,
                            Title = "Гваделупа"
                        },
                        new
                        {
                            Id = 141,
                            Title = "Гренландия"
                        },
                        new
                        {
                            Id = 142,
                            Title = "Гвинея-Бисау"
                        },
                        new
                        {
                            Id = 143,
                            Title = "Макао"
                        },
                        new
                        {
                            Id = 144,
                            Title = "Парагвай"
                        },
                        new
                        {
                            Id = 145,
                            Title = "Мавритания"
                        },
                        new
                        {
                            Id = 146,
                            Title = "Руанда"
                        },
                        new
                        {
                            Id = 147,
                            Title = "Фарерские острова"
                        },
                        new
                        {
                            Id = 148,
                            Title = "Кот-д’Ивуар"
                        },
                        new
                        {
                            Id = 149,
                            Title = "Гибралтар"
                        },
                        new
                        {
                            Id = 150,
                            Title = "Ботсвана"
                        },
                        new
                        {
                            Id = 151,
                            Title = "Боливия"
                        },
                        new
                        {
                            Id = 152,
                            Title = "Мадагаскар"
                        },
                        new
                        {
                            Id = 153,
                            Title = "Кабо-Верде"
                        },
                        new
                        {
                            Id = 154,
                            Title = "Чад"
                        },
                        new
                        {
                            Id = 155,
                            Title = "Мали"
                        },
                        new
                        {
                            Id = 156,
                            Title = "Фиджи"
                        },
                        new
                        {
                            Id = 157,
                            Title = "Бутан"
                        },
                        new
                        {
                            Id = 158,
                            Title = "Барбадос"
                        },
                        new
                        {
                            Id = 159,
                            Title = "Тринидад и Тобаго"
                        },
                        new
                        {
                            Id = 160,
                            Title = "Мозамбик"
                        },
                        new
                        {
                            Id = 161,
                            Title = "Заир"
                        },
                        new
                        {
                            Id = 162,
                            Title = "Андорра"
                        },
                        new
                        {
                            Id = 163,
                            Title = "Туркменистан"
                        },
                        new
                        {
                            Id = 164,
                            Title = "Гайана"
                        },
                        new
                        {
                            Id = 165,
                            Title = "Корея"
                        },
                        new
                        {
                            Id = 166,
                            Title = "Нигер"
                        },
                        new
                        {
                            Id = 167,
                            Title = "Конго"
                        },
                        new
                        {
                            Id = 168,
                            Title = "Того"
                        },
                        new
                        {
                            Id = 169,
                            Title = "Ватикан"
                        },
                        new
                        {
                            Id = 170,
                            Title = "Черногория"
                        },
                        new
                        {
                            Id = 171,
                            Title = "Бурунди"
                        },
                        new
                        {
                            Id = 172,
                            Title = "Папуа - Новая Гвинея"
                        },
                        new
                        {
                            Id = 173,
                            Title = "Бахрейн"
                        },
                        new
                        {
                            Id = 174,
                            Title = "Гондурас"
                        },
                        new
                        {
                            Id = 175,
                            Title = "Судан"
                        },
                        new
                        {
                            Id = 176,
                            Title = "Эфиопия"
                        },
                        new
                        {
                            Id = 177,
                            Title = "Йемен"
                        },
                        new
                        {
                            Id = 178,
                            Title = "Вьетнам Северный"
                        },
                        new
                        {
                            Id = 179,
                            Title = "Суринам"
                        },
                        new
                        {
                            Id = 180,
                            Title = "Маврикий"
                        },
                        new
                        {
                            Id = 181,
                            Title = "Белиз"
                        },
                        new
                        {
                            Id = 182,
                            Title = "Либерия"
                        },
                        new
                        {
                            Id = 183,
                            Title = "Лесото"
                        },
                        new
                        {
                            Id = 184,
                            Title = "Уганда"
                        },
                        new
                        {
                            Id = 185,
                            Title = "Каймановы острова"
                        },
                        new
                        {
                            Id = 186,
                            Title = "Антигуа и Барбуда"
                        },
                        new
                        {
                            Id = 187,
                            Title = "Западная Сахара"
                        },
                        new
                        {
                            Id = 188,
                            Title = "Сан-Марино"
                        },
                        new
                        {
                            Id = 189,
                            Title = "Гуам"
                        },
                        new
                        {
                            Id = 190,
                            Title = "Косово"
                        },
                        new
                        {
                            Id = 191,
                            Title = "Лаос"
                        },
                        new
                        {
                            Id = 192,
                            Title = "Катар"
                        },
                        new
                        {
                            Id = 193,
                            Title = "Оман"
                        },
                        new
                        {
                            Id = 194,
                            Title = "Американские Виргинские острова"
                        },
                        new
                        {
                            Id = 195,
                            Title = "Сиам"
                        },
                        new
                        {
                            Id = 196,
                            Title = "Сьерра-Леоне"
                        },
                        new
                        {
                            Id = 197,
                            Title = "Эритрея"
                        },
                        new
                        {
                            Id = 198,
                            Title = "Сомали"
                        },
                        new
                        {
                            Id = 199,
                            Title = "Доминика"
                        },
                        new
                        {
                            Id = 200,
                            Title = "Бирма"
                        },
                        new
                        {
                            Id = 201,
                            Title = "Реюньон"
                        },
                        new
                        {
                            Id = 202,
                            Title = "Федеративные Штаты Микронезии"
                        },
                        new
                        {
                            Id = 203,
                            Title = "Самоа"
                        },
                        new
                        {
                            Id = 204,
                            Title = "Американское Самоа"
                        },
                        new
                        {
                            Id = 205,
                            Title = "Свазиленд"
                        },
                        new
                        {
                            Id = 206,
                            Title = "Французская Полинезия"
                        },
                        new
                        {
                            Id = 207,
                            Title = "Мьянма"
                        },
                        new
                        {
                            Id = 208,
                            Title = "Новая Каледония"
                        },
                        new
                        {
                            Id = 209,
                            Title = "Французская Гвиана"
                        },
                        new
                        {
                            Id = 210,
                            Title = "Сент-Винсент и Гренадины"
                        },
                        new
                        {
                            Id = 211,
                            Title = "Малави"
                        },
                        new
                        {
                            Id = 212,
                            Title = "Экваториальная Гвинея"
                        },
                        new
                        {
                            Id = 213,
                            Title = "Коморы"
                        },
                        new
                        {
                            Id = 214,
                            Title = "Кирибати"
                        },
                        new
                        {
                            Id = 215,
                            Title = "Тувалу"
                        },
                        new
                        {
                            Id = 216,
                            Title = "Тимор-Лесте"
                        },
                        new
                        {
                            Id = 217,
                            Title = "ЦАР"
                        },
                        new
                        {
                            Id = 218,
                            Title = "Тонга"
                        },
                        new
                        {
                            Id = 219,
                            Title = "Гренада"
                        },
                        new
                        {
                            Id = 220,
                            Title = "Гамбия"
                        },
                        new
                        {
                            Id = 221,
                            Title = "Антарктида"
                        },
                        new
                        {
                            Id = 222,
                            Title = "Острова Кука"
                        },
                        new
                        {
                            Id = 223,
                            Title = "Остров Мэн"
                        },
                        new
                        {
                            Id = 224,
                            Title = "Внешние малые острова США"
                        },
                        new
                        {
                            Id = 225,
                            Title = "Монтсеррат"
                        },
                        new
                        {
                            Id = 226,
                            Title = "Маршалловы острова"
                        },
                        new
                        {
                            Id = 227,
                            Title = "Бруней-Даруссалам"
                        },
                        new
                        {
                            Id = 228,
                            Title = "Сейшельские острова"
                        },
                        new
                        {
                            Id = 229,
                            Title = "Палау"
                        },
                        new
                        {
                            Id = 230,
                            Title = "Сент-Люсия"
                        },
                        new
                        {
                            Id = 231,
                            Title = "Вануату"
                        },
                        new
                        {
                            Id = 232,
                            Title = "Мальдивы"
                        },
                        new
                        {
                            Id = 233,
                            Title = "Босния"
                        },
                        new
                        {
                            Id = 234,
                            Title = "Уоллис и Футуна"
                        },
                        new
                        {
                            Id = 235,
                            Title = "Белоруссия"
                        },
                        new
                        {
                            Id = 236,
                            Title = "Киргизия"
                        },
                        new
                        {
                            Id = 239,
                            Title = "Джибути"
                        },
                        new
                        {
                            Id = 240,
                            Title = "Виргинские Острова (США)"
                        },
                        new
                        {
                            Id = 241,
                            Title = "Северная Македония"
                        },
                        new
                        {
                            Id = 242,
                            Title = "Виргинские Острова (Великобритания)"
                        },
                        new
                        {
                            Id = 3545269,
                            Title = "Сент-Люсия "
                        },
                        new
                        {
                            Id = 3781461,
                            Title = "Сент-Китс и Невис"
                        },
                        new
                        {
                            Id = 3985922,
                            Title = "Соломоновы Острова"
                        },
                        new
                        {
                            Id = 4336645,
                            Title = "Виргинские Острова"
                        },
                        new
                        {
                            Id = 7801402,
                            Title = "Фолклендские острова"
                        },
                        new
                        {
                            Id = 10842163,
                            Title = "Остров Святой Елены"
                        },
                        new
                        {
                            Id = 32518739,
                            Title = "острова Теркс и Кайкос"
                        },
                        new
                        {
                            Id = 47738117,
                            Title = "Мелкие отдаленные острова США"
                        },
                        new
                        {
                            Id = 65870322,
                            Title = "Сан-Томе и Принсипи"
                        },
                        new
                        {
                            Id = 100999433,
                            Title = "Эсватини"
                        },
                        new
                        {
                            Id = 121519792,
                            Title = "Шпицберген и Ян-Майен"
                        });
                });

            modelBuilder.Entity("CinemaRoulette.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cinema")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("CinemaRoulette.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "триллер"
                        },
                        new
                        {
                            Id = 2,
                            Title = "драма"
                        },
                        new
                        {
                            Id = 3,
                            Title = "криминал"
                        },
                        new
                        {
                            Id = 4,
                            Title = "мелодрама"
                        },
                        new
                        {
                            Id = 5,
                            Title = "детектив"
                        },
                        new
                        {
                            Id = 6,
                            Title = "фантастика"
                        },
                        new
                        {
                            Id = 7,
                            Title = "приключения"
                        },
                        new
                        {
                            Id = 8,
                            Title = "биография"
                        },
                        new
                        {
                            Id = 9,
                            Title = "фильм-нуар"
                        },
                        new
                        {
                            Id = 10,
                            Title = "вестерн"
                        },
                        new
                        {
                            Id = 11,
                            Title = "боевик"
                        },
                        new
                        {
                            Id = 12,
                            Title = "фэнтези"
                        },
                        new
                        {
                            Id = 13,
                            Title = "комедия"
                        },
                        new
                        {
                            Id = 14,
                            Title = "военный"
                        },
                        new
                        {
                            Id = 15,
                            Title = "история"
                        },
                        new
                        {
                            Id = 16,
                            Title = "музыка"
                        },
                        new
                        {
                            Id = 17,
                            Title = "ужасы"
                        },
                        new
                        {
                            Id = 18,
                            Title = "мультфильм"
                        },
                        new
                        {
                            Id = 19,
                            Title = "семейный"
                        },
                        new
                        {
                            Id = 20,
                            Title = "мюзикл"
                        },
                        new
                        {
                            Id = 21,
                            Title = "спорт"
                        },
                        new
                        {
                            Id = 22,
                            Title = "документальный"
                        },
                        new
                        {
                            Id = 23,
                            Title = "короткометражка"
                        },
                        new
                        {
                            Id = 24,
                            Title = "аниме"
                        },
                        new
                        {
                            Id = 25,
                            Title = ""
                        },
                        new
                        {
                            Id = 26,
                            Title = "новости"
                        },
                        new
                        {
                            Id = 27,
                            Title = "концерт"
                        },
                        new
                        {
                            Id = 28,
                            Title = "для взрослых"
                        },
                        new
                        {
                            Id = 29,
                            Title = "церемония"
                        },
                        new
                        {
                            Id = 30,
                            Title = "реальное ТВ"
                        },
                        new
                        {
                            Id = 31,
                            Title = "игра"
                        },
                        new
                        {
                            Id = 32,
                            Title = "ток-шоу"
                        },
                        new
                        {
                            Id = 33,
                            Title = "детский"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
